### PR TITLE
Modified .gitignore entry "BuildOutput.txt" to "BuildOutput.xml"

### PR DESCRIPTION
**Pull request by JLSolutionsNET**

### CODE REVIEW

**Comment by JLSolutionsNET** [comment]
BuildOutput.xml is always generated after each local build. I have not yet noticed any BuildOutput.txt file.

BuildOutputXml

**Comment by freddydk** [comment]
The problem here is that you have a file called .xml (this is clearly not an .xml file)
Is this file created when you build in VS Code?

AL-Go for GitHub does create a BuildOutput.txt during builds in workflows - you don't have anything in your vs code settings?

**Comment by freddydk** [comment]
I can see that this happens when running localdevenv - will check why

**Comment by freddydk** [comment]
The problem is in ContainerHelper.
Will fix this asap.

**Comment by JLSolutionsNET** [comment]
No need to merge

**Pull request closed without merging**
